updated Day27
Sravanigaju/Qxf2_internship_22 pull request #29
Opened 2023-01-18 06:57 UTC by Sravanigaju

2023-01-18 07:45 UTC, Sravanigaju commented
![](https://github.trello.services/images/mini-trello-icon.png) [update day 27[shravani]](https://trello.com/c/d6nERZcT/44-update-day-27shravani)

2023-01-18 07:51 UTC, shivahari requested changes
Can you add the list of exercise too

2023-01-18 10:10 UTC, ambigai-rajan approved these changes

2023-01-19 04:43 UTC, shivahari approved these changes

2023-01-19 04:55 UTC, merged